### ISSUE TITLE
share button crashes on iOS8

### ISSUE THREAD

**Issue by ebgraham** [TransitApp/SVWebViewController#108]
Using the modal web view controller in an iPad page sheet, clicking the share button gives:

<blockquote>
Terminating app due to uncaught exception 'NSGenericException', reason: 'UIPopoverPresentationController (<_UIAlertControllerActionSheetRegularPresentationController: 0x7fb38c8e7fe0>) should have a non-nil sourceView or barButtonItem set before the presentation occurs.'
</blockquote>

**Comment by scinfu** [comment]
this bug persists in ios 9
