### ISSUE TITLE
iOS8 can not set property barsTintColor

### ISSUE THREAD

**Issue by ykws** [TransitApp/SVWebViewController#118]
Maybe iOS8 quickly show web view controller before call viewWillAppear,
cause of can not set property.

**Comment by kmiloaguilar** [comment]
With this is it possible to change the color?

**Comment by ykws** [comment]
Yes, possible.
But it is no need this commit, because it can change the color.

```objective-c
SVModalWebViewController *webViewController = [[SVModalWebViewController alloc] initWithURL:URL];
webViewController.barsTintColor = [UIColor blackColor];

**Comment by kmiloaguilar** [comment]
Thanks!
