### ISSUE TITLE
WebView not working in iOS 9

### ISSUE THREAD

**Issue by sgrmhn** [TransitApp/SVWebViewController#138]
Hello there,

I was wondering if you noticed that this library is not working properly in iOS 9. When webview is loaded, it only shows the blank screen in the device or simulator. It was working fine up to iOS 8.4.
![ios8](https://cloud.githubusercontent.com/assets/6771029/10274083/5a010026-6b59-11e5-91d2-871c90d5f0cc.png)
![ios9](https://cloud.githubusercontent.com/assets/6771029/10274097/7ea1273a-6b59-11e5-9fb4-deeaa9b5616f.png)

**Comment by manmal** [comment]
+1!

**Comment by manmal** [comment]
@sgrmhn we use SFSafariViewController on iOS9, perhaps this is an option for you.

**Comment by manmal** [comment]
@sgrmhn turns out this is related to app transport security. i didn't think of that first because SafariViewController DID work. here is the fix: http://stackoverflow.com/a/32766083/458603

**Comment by sgrmhn** [comment]
@manmal thanks for the reply... Yup issue was related to the app transport security issue for iOS 9 and I had already fixed the issue in my thanks.. Thanks for the reply though... :)

**Comment by licx** [comment]
I suggest you add some warning to the README about adding NSAppTransportSecurity to Info.plist on iOS9
